language: node_js
node_js:
- lts/*
install:
- npm ci
script:
- npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github_token:
    secure: RnhazPpaK83juTdCEo91qMLkISwttwCAdpOq7/YkYFwRYvLjqPdFrPEAoid11YrudKVsK8HCWNS+Y/DOQvsrQfOLFuNOH8d7gWfMedpAM9O9hdOzWnXG38RN0em6wP/TjimFV9VDcMIGQVkFiJaPsMIl/3KclajLpcS4NNej+HaFPHFZmfPiPNVTbANTvnDDXqnYjwi8tAAuBHSPYT1pdcr5yfyl8NNLZCnlnVnTz0pqjtxRHFpkTXMrPifoHTPIHrMteGo4crR+ljZl3Qu1MunCtvuhGWmGF4Q3uzbG1MWyGk/KSISiAMjfbx+zAuNrK232Wggf7eM39tj85o/2CfLiKzDEfeJnwYcnaiyzd9xf5GhOpRDGGGJ0X6s5bpaeTsRTBfWDxLoqbqP2P3qGI/AthTz4EgYmaIuFGMU45GR7bxvUNVr6/FkX1Ukrnls53UThBsuiJYSPiIF9Dwfh88k6WJRKzzdcgpL13s69eN8985HAd+X90GWzHg0yRNacxHQ3PyjnR2uPcMtdc1FTRhCXaEbWtvT6Tll83RNzE11KQaNeQ4pZA7PWsOWWMPezKETkizgZA1mBchhoDRY8aZg8RH2ncJOvABa84NuH0cM7Kfed24PcEQYXWQDXTh8UeIjDyT8PTuwT+Az0qKZ9EkRY4/uUufwwadUMXYnOwrY=
  keep-history: true
  on:
    branch: master
